# Generated by Django 4.1.3 on 2022-11-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('price', models.IntegerField(blank=True, default='', null=True)),
                ('change', models.FloatField(blank=True, default='', null=True)),
            ],
        ),
    ]
