# Generated by Django 4.1.3 on 2022-11-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_insidertransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('market_cap', models.TextField(blank=True, default='', null=True)),
                ('pe_ratio', models.FloatField(blank=True, default='', null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stock')),
            ],
        ),
    ]
