# Generated by Django 4.1.3 on 2022-11-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_valuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='market_cap',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
